repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/google/yapf
    rev: v0.40.2
    hooks:
      - id: yapf
