# @package _global_
defaults:
- override /env/glider/air_velocity_field@_here_: multi_agent_thermal_wind_turbulence
- _self_
random_state:
  generator_name: PCG64
  encoded_state_values: gASVLgAAAAAAAABdlChLAEsAihFTV1mpGv3LBusBn_4RDi6MAIoQwb8nCkKzLES32UL1dKOoH2Uu
