# @package _global_
defaults:
- override /env/glider/air_velocity_field@_here_: multi_agent_thermal_wind
- _self_
random_state:
  generator_name: PCG64
  encoded_state_values: gASVLwAAAAAAAABdlChLAEsAihHtjMjxfVJmq1C7ksi-Q7XLAIoRO3Y_lcAUqj3ua0CYPDsquwBlLg==
