# @package _global_
defaults:
- override /env/glider/air_velocity_field@_here_: multi_agent_thermal_wind_turbulence
- _self_
random_state:
  generator_name: PCG64
  encoded_state_values: gASVLQAAAAAAAABdlChLAEsAihBx-v6k7vuT1oDDEpngkLQIihABB6hRN7F0XF0uvgzlcudUZS4=
