# @package _global_
defaults:
- override /env/glider/air_velocity_field@_here_: multi_agent_thermal_wind
- _self_
random_state:
  generator_name: PCG64
  encoded_state_values: gASVLgAAAAAAAABdlChLAEsAihCr7mZbEXpoIjhXgvn83PIaihH9K2wTnv1h-Q_8Z3Emz0TOAGUu
