defaults:
  - multi_agent_eval_teacher_alone_base_config
  - _self_

  
evaluators:
  main:
    env:
      env:
        params:
          initial_conditions_params:
            tangent_position_parameters:
              starting_distance_from_tangent_position_m_normal_mean: 150.0
              starting_distance_from_tangent_position_m_normal_sigma: 0.0
              starting_distance_from_tangent_position_m_normal_sigma_k: 1.
              tangent_distance_from_core_m_normal_mean: 10.0
              tangent_distance_from_core_m_normal_sigma: 0.0
              tangent_distance_from_core_m_normal_sigma_k: 1.
